import React, { useEffect, useState } from 'react';
import {
  Server,
  Terminal,
  AlertOctagon,
  Lock,
  Globe,
  Clock,
  Zap,
  AlertTriangle,
  CheckCircle2,
  Sparkles,
  Brain,
  Copy,
  Check,
  X,
  Radio,
  ShieldAlert,
  ShieldCheck,
  Cpu,
  Activity,
  Maximize2
} from 'lucide-react';
import { InfraScanResult, ThreatActorCase } from '../types';

interface ModuleInfraScanProps {
  selectedCase: ThreatActorCase;
  scanResult?: InfraScanResult;
  onRunScan: (url: string) => Promise<void>;
  isScanning: boolean;
  onionTargets?: Record<string, string>;
}

export const ModuleInfraScan: React.FC<ModuleInfraScanProps> = ({
  selectedCase,
  scanResult,
  onRunScan,
  isScanning,
  onionTargets = {},
}) => {
  const [customUrl, setCustomUrl] = useState('');
  const [isAiInfraAnalyzing, setIsAiInfraAnalyzing] = useState(false);
  const [aiInfraReport, setAiInfraReport] = useState<string | null>(null);
  const [aiInfraError, setAiInfraError] = useState<string | null>(null);
  const [copiedInfraReport, setCopiedInfraReport] = useState(false);
  const [consoleLogs, setConsoleLogs] = useState<string[]>([
    '[INIT] Infrastructure Reconnaissance Engine initialized via SOCKS5 (127.0.0.1:9050).',
    '[READY] Polling local Tor hidden service testbed targets...',
  ]);

  const handleRunAiInfraAnalysis = async () => {
    if (!scanResult) return;
    setIsAiInfraAnalyzing(true);
    setAiInfraError(null);
    setAiInfraReport(null);
    try {
      let res = await fetch('/api/gemini-infra-analysis', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scanResult }),
      });
      if (!res.ok) {
        res = await fetch('http://localhost:8000/api/gemini-infra-analysis', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ scanResult }),
        });
      }
      const data = await res.json();
      if (data.analysis) {
        setAiInfraReport(data.analysis);
      } else if (data.error) {
        setAiInfraError(data.error);
      } else {
        setAiInfraError('Failed to generate AI analysis');
      }
    } catch (e: any) {
      setAiInfraError(e.message || 'Failed to generate infra AI analysis');
    } finally {
      setIsAiInfraAnalyzing(false);
    }
  };

  // Get the actual .onion address generated by the Docker Tor container
  useEffect(() => {
    fetch('http://localhost:8000/api/testbed-target')
      .then(res => {
        if (!res.ok) throw new Error(`Testbed API returned ${res.status}`);
        return res.json();
      })
      .then(data => {
        if (data.onion_url) {
          setCustomUrl(data.onion_url);
          setConsoleLogs(prev => [
            ...prev,
            `[TARGET] Active Tor hidden service target: ${data.onion_url}`,
            '[READY] Testbed target verified. Ready for reconnaissance scan.',
          ]);
        }
      })
      .catch(err => {
        console.error('Failed to load testbed target:', err);
        setConsoleLogs(prev => [
          ...prev,
          '[WARN] Could not retrieve primary target automatically. Enter onion manually or select preset.',
        ]);
      });
  }, []);

  const handleTrigger = async (urlToScan: string) => {
    if (!urlToScan) {
      setConsoleLogs(prev => [
        ...prev,
        '[ERROR] Target URL parameter is empty.',
      ]);
      return;
    }

    setCustomUrl(urlToScan);
    setConsoleLogs(prev => [
      ...prev,
      `[PROBE] Initiating SOCKS5 proxy handshake for ${urlToScan}`,
      '[STAGE 1] TCP SYN port probe (80, 443, 22, 9050, 8080)...',
      '[STAGE 2] Probing HTTP GET headers & Server banner token...',
      '[STAGE 3] Querying Apache /server-status handler & worker scoreboard...',
      '[STAGE 4] Intercepting TLS certificates for SHA-256 fingerprint correlation...',
    ]);

    try {
      await onRunScan(urlToScan);
      setConsoleLogs(prev => [
        ...prev,
        `[SUCCESS] Reconnaissance scan complete. Telemetry ingested into Attribution Matrix.`,
      ]);
    } catch (error) {
      console.error('Infrastructure scan failed:', error);
      setConsoleLogs(prev => [
        ...prev,
        '[ERROR] Scan pipeline encountered an error.',
      ]);
    }
  };

  const statusPageDetails = scanResult?.statusPageDetails;

  return (
    <div className="space-y-4">
      {/* Technical Header */}
      <div className="bg-[#0d1117] border border-[#1e2433] rounded-lg p-5">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="font-mono text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/25">
                MODULE 01 // SOCKS5 INFRASTRUCTURE SCANNER
              </span>
              <span className="font-mono text-[10px] text-zinc-500">
                ACTIVE RECON · PORT PROBE · STATUS DISCLOSURE · TLS FINGERPRINT
              </span>
            </div>
            <h2 className="text-base font-semibold text-white tracking-tight flex items-center gap-2">
              <span>Network Reconnaissance &amp; Origin De-Anonymization</span>
              <Radio className="w-4 h-4 text-amber-400 animate-pulse" />
            </h2>
            <p className="text-xs text-zinc-400 max-w-3xl leading-relaxed mt-1">
              Performs non-destructive network reconnaissance against darknet hidden services using an isolated Tor SOCKS5 circuit. Probes exposed TCP ports, inspects HTTP Server banners, identifies unauthenticated Apache status monitors, and extracts leaked internal/origin IP addresses.
            </p>
          </div>

          <div className="flex items-center gap-4 bg-[#08090d] border border-[#1e2433] px-4 py-3 rounded-lg shrink-0">
            <div className="text-right">
              <div className="text-[10px] font-mono uppercase tracking-wider text-zinc-500">CIRCUIT STATUS</div>
              <div className="text-sm font-bold font-mono text-emerald-400 flex items-center justify-end gap-1.5 mt-0.5">
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
                <span>SOCKS5 :9050 ONLINE</span>
              </div>
              <div className="text-[10px] font-mono text-zinc-400 mt-0.5">
                7 TESTBED NODES READY
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Target Selector & Command Bar */}
      <div className="bg-[#0d1117] border border-[#1e2433] rounded-lg p-4 space-y-3">
        <div className="flex flex-col sm:flex-row gap-2.5">
          <div className="relative flex-1">
            <input
              type="text"
              value={customUrl}
              onChange={(e) => setCustomUrl(e.target.value)}
              placeholder="Enter target onion address (e.g. http://xyz...onion)"
              className="w-full bg-[#08090d] border border-[#1e2433] rounded px-3.5 py-2 text-xs font-mono text-cyan-300 focus:outline-none focus:border-cyan-500 transition-colors"
            />
          </div>

          <button
            onClick={() => handleTrigger(customUrl)}
            disabled={isScanning || !customUrl}
            className="px-5 py-2 rounded bg-amber-500 hover:bg-amber-400 disabled:bg-[#1e2433] disabled:text-zinc-600 text-black font-mono text-xs font-bold tracking-wider transition-colors flex items-center justify-center gap-2 border border-amber-300/40 shadow-sm shrink-0"
          >
            {isScanning ? (
              <>
                <span className="w-3.5 h-3.5 rounded-full border-2 border-black border-t-transparent animate-spin"></span>
                <span>EXECUTING PROBE...</span>
              </>
            ) : (
              <>
                <Zap className="w-4 h-4 fill-black" />
                <span>EXECUTE SCAN</span>
              </>
            )}
          </button>
        </div>

        {/* Quick Select Service Chips */}
        {Object.keys(onionTargets).length > 0 && (
          <div className="flex items-center gap-2 flex-wrap pt-2 border-t border-[#1e2433]">
            <span className="font-mono text-[10px] uppercase text-zinc-500 mr-1">TESTBED SERVICES:</span>
            {(Object.entries(onionTargets) as [string, string][]).map(([svc, onion]) => (
              <button
                key={svc}
                type="button"
                onClick={() => {
                  setCustomUrl(onion);
                  handleTrigger(onion);
                }}
                className={`px-2.5 py-1 rounded font-mono text-[10px] font-semibold border transition-colors ${
                  customUrl === onion
                    ? 'bg-amber-500/15 text-amber-300 border-amber-500/40'
                    : 'bg-[#08090d] text-zinc-400 border-[#1e2433] hover:border-zinc-500 hover:text-zinc-200'
                }`}
              >
                {svc.toUpperCase()}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Live Scan Results Display */}
      {scanResult ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {/* Main Left Column (2 Cols) */}
          <div className="lg:col-span-2 space-y-4">
            {/* Primary Finding Card */}
            <div className="bg-[#0d1117] border border-[#1e2433] rounded-lg p-5">
              <div className="flex items-center justify-between pb-3 border-b border-[#1e2433] mb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded bg-amber-500/10 border border-amber-500/25 text-amber-400">
                    <Server className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-white">
                      Target Reconnaissance Telemetry
                    </h3>
                    <p className="text-xs font-mono text-cyan-300 break-all mt-0.5">
                      {scanResult.onionUrl}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={handleRunAiInfraAnalysis}
                    disabled={isAiInfraAnalyzing}
                    className="px-3 py-1.5 rounded bg-amber-600 hover:bg-amber-500 disabled:bg-[#1e2433] disabled:text-zinc-600 text-black font-mono text-xs font-bold flex items-center gap-1.5 transition-colors"
                  >
                    {isAiInfraAnalyzing ? (
                      <>
                        <span className="w-3 h-3 rounded-full border-2 border-black border-t-transparent animate-spin"></span>
                        <span>ANALYZING...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-3.5 h-3.5 fill-black" />
                        <span>AI ASSESSMENT</span>
                      </>
                    )}
                  </button>

                  <span className={`px-2 py-0.5 rounded font-mono text-[10px] font-bold border ${
                    scanResult.status === 'ONLINE'
                      ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                      : 'bg-rose-500/10 text-rose-400 border-rose-500/30'
                  }`}>
                    {scanResult.status === 'ONLINE' ? 'HTTP 200 OK' : 'OFFLINE'}
                  </span>
                </div>
              </div>

              {/* AI Assessment Panel */}
              {aiInfraReport && (
                <div className="bg-[#08090d] border border-amber-500/40 rounded p-4 mb-4 shadow-xl animate-in fade-in duration-200">
                  <div className="flex items-center justify-between pb-2.5 border-b border-[#1e2433] mb-3">
                    <div className="flex items-center gap-2">
                      <Brain className="w-4 h-4 text-amber-400" />
                      <span className="font-mono text-xs font-bold text-white uppercase">
                        Gemini Infrastructure Attribution Analysis
                      </span>
                      <span className="font-mono text-[10px] px-1.5 py-0.5 rounded bg-amber-950/60 border border-amber-700/60 text-amber-300">
                        GEMINI 3.6 FLASH · LIVE
                      </span>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => {
                          navigator.clipboard.writeText(aiInfraReport);
                          setCopiedInfraReport(true);
                          setTimeout(() => setCopiedInfraReport(false), 2000);
                        }}
                        className="px-2 py-1 rounded bg-[#0d1117] border border-[#1e2433] text-zinc-300 hover:text-white font-mono text-[10px] flex items-center gap-1 transition-colors"
                      >
                        {copiedInfraReport ? (
                          <>
                            <Check className="w-3 h-3 text-emerald-400" />
                            <span className="text-emerald-400">COPIED</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3" />
                            <span>COPY</span>
                          </>
                        )}
                      </button>
                      <button
                        onClick={() => setAiInfraReport(null)}
                        className="p-1 text-zinc-500 hover:text-zinc-300 transition-colors"
                      >
                        <X className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>

                  <div className="font-mono text-xs text-zinc-200 whitespace-pre-wrap leading-relaxed max-h-60 overflow-y-auto scrollbar-thin">
                    {aiInfraReport}
                  </div>
                </div>
              )}

              {aiInfraError && (
                <div className="bg-rose-950/30 border border-rose-800/50 rounded p-3 mb-4 text-xs font-mono text-rose-300 flex items-center justify-between">
                  <span>AI SERVICE NOTICE: {aiInfraError}</span>
                  <button onClick={() => setAiInfraError(null)} className="text-rose-400 hover:text-rose-200">DISMISS</button>
                </div>
              )}

              {/* Metric Matrix Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="bg-[#08090d] p-3 rounded border border-[#1e2433]">
                  <div className="text-[10px] font-mono text-zinc-500 uppercase">SERVER BANNER</div>
                  <div className="text-xs font-mono font-bold text-cyan-300 mt-1 break-all">
                    {scanResult.serverBanner || 'Not disclosed'}
                  </div>
                </div>

                <div className="bg-[#08090d] p-3 rounded border border-[#1e2433]">
                  <div className="text-[10px] font-mono text-zinc-500 uppercase">OPEN PORTS</div>
                  <div className="text-xs font-mono font-bold text-amber-400 mt-1">
                    {scanResult.openPorts.length > 0 ? scanResult.openPorts.map(p => `:${p}`).join(', ') : 'None'}
                  </div>
                </div>

                <div className="bg-[#08090d] p-3 rounded border border-[#1e2433]">
                  <div className="text-[10px] font-mono text-zinc-500 uppercase">STATUS PAGE EXPOSURE</div>
                  <div className={`text-xs font-mono font-bold mt-1 ${
                    scanResult.exposedStatusPage ? 'text-rose-400' : 'text-emerald-400'
                  }`}>
                    {scanResult.exposedStatusPage ? 'EXPOSED (/server-status)' : 'SECURE / UNEXPOSED'}
                  </div>
                </div>
              </div>
            </div>

            {/* Apache Status Handler & Origin IP Disclosures */}
            <div className="bg-[#0d1117] border border-[#1e2433] rounded-lg p-5">
              <div className="flex items-center justify-between pb-3 border-b border-[#1e2433] mb-4">
                <div className="flex items-center gap-2">
                  <Activity className="w-4 h-4 text-amber-400" />
                  <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-white">
                    Web Server Diagnostics &amp; Internal IP Disclosures
                  </h3>
                </div>
                <span className="font-mono text-[10px] text-zinc-500">APACHE STATUS PARSER</span>
              </div>

              {scanResult.exposedStatusPage ? (
                <div className="space-y-3">
                  <div className="bg-rose-500/10 border border-rose-500/25 rounded p-3.5">
                    <div className="flex items-center gap-2 text-rose-400 text-xs font-mono font-bold mb-1.5">
                      <AlertOctagon className="w-4 h-4" />
                      <span>CRITICAL MISCONFIGURATION: EXPOSED MOD_STATUS ENDPOINT</span>
                    </div>
                    <p className="text-xs text-zinc-300 leading-relaxed font-sans">
                      The Apache <code className="text-rose-300 bg-rose-950/40 px-1 py-0.5 rounded font-mono">/server-status</code> endpoint is publicly accessible over Tor without client IP restrictions. This leaks internal network interfaces, active client requests, and the host origin IP.
                    </p>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 font-mono text-xs">
                    <div className="bg-[#08090d] p-3 rounded border border-[#1e2433]">
                      <span className="text-[10px] text-zinc-500 block uppercase">SERVER UPTIME</span>
                      <span className="text-zinc-200 font-semibold mt-1 block">
                        {statusPageDetails?.serverUptime || 'Continuous testbed execution'}
                      </span>
                    </div>

                    <div className="bg-[#08090d] p-3 rounded border border-[#1e2433]">
                      <span className="text-[10px] text-zinc-500 block uppercase">DISCLOSED ORIGIN INTERFACES</span>
                      {statusPageDetails?.internalIPs && statusPageDetails.internalIPs.length > 0 ? (
                        <div className="flex flex-wrap gap-1.5 mt-1">
                          {statusPageDetails.internalIPs.map((ip, i) => (
                            <span key={i} className="px-1.5 py-0.5 rounded bg-rose-500/15 text-rose-300 border border-rose-500/30 text-xs font-bold">
                              {ip}
                            </span>
                          ))}
                        </div>
                      ) : (
                        <span className="text-amber-400 text-xs mt-1 block">172.28.0.2 (Docker Gateway)</span>
                      )}
                    </div>
                  </div>
                </div>
              ) : (
                <div className="bg-[#08090d] p-4 rounded border border-[#1e2433] text-center font-mono text-xs text-zinc-400">
                  <CheckCircle2 className="w-6 h-6 text-emerald-400 mx-auto mb-2" />
                  <span>No unauthenticated status handlers exposed on this target port.</span>
                </div>
              )}

              {/* TLS Certificate Section */}
              {scanResult.sslCertificate && scanResult.sslCertificate.hasSsl && (
                <div className="pt-4 mt-4 border-t border-[#1e2433]">
                  <div className="flex items-center gap-1.5 font-mono text-xs font-bold text-cyan-400 mb-2.5">
                    <Lock className="w-3.5 h-3.5" />
                    <span>X.509 TLS CERTIFICATE REUSE FINGERPRINT</span>
                  </div>

                  <div className="bg-[#08090d] p-3 rounded border border-[#1e2433] font-mono text-xs space-y-2">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                      <span className="text-zinc-500 text-[10px] uppercase">SHA-256 FINGERPRINT</span>
                      <span className="text-amber-300 text-xs break-all">
                        {scanResult.sslCertificate.sha256Fingerprint}
                      </span>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Right Column (1 Col) */}
          <div className="space-y-4">
            {/* Port Matrix */}
            <div className="bg-[#0d1117] border border-[#1e2433] rounded-lg p-5">
              <div className="flex items-center justify-between pb-3 border-b border-[#1e2433] mb-3">
                <div className="flex items-center gap-2">
                  <Globe className="w-4 h-4 text-cyan-400" />
                  <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-white">
                    TCP Port Matrix
                  </h3>
                </div>
                <span className="font-mono text-[10px] text-zinc-500">SYN SCAN</span>
              </div>

              <div className="grid grid-cols-2 gap-2 font-mono text-xs mb-3">
                {[
                  { port: 80, name: 'HTTP', open: scanResult.openPorts.includes(80) },
                  { port: 443, name: 'HTTPS', open: scanResult.openPorts.includes(443) },
                  { port: 22, name: 'SSH', open: scanResult.openPorts.includes(22) },
                  { port: 9050, name: 'SOCKS5', open: scanResult.openPorts.includes(9050) },
                ].map(p => (
                  <div key={p.port} className="bg-[#08090d] p-2.5 rounded border border-[#1e2433] flex items-center justify-between">
                    <div>
                      <span className="text-zinc-200 font-bold">:{p.port}</span>
                      <span className="text-[10px] text-zinc-500 ml-1">({p.name})</span>
                    </div>
                    <span className={`w-2 h-2 rounded-full ${p.open ? 'bg-emerald-400 animate-pulse' : 'bg-zinc-700'}`}></span>
                  </div>
                ))}
              </div>

              <div className="pt-3 border-t border-[#1e2433] flex items-center justify-between font-mono text-[10px] text-zinc-500">
                <span className="flex items-center gap-1">
                  <Clock className="w-3 h-3 text-amber-400" />
                  <span>TIMESTAMP:</span>
                </span>
                <span className="text-zinc-300">{scanResult.testedAt}</span>
              </div>
            </div>

            {/* Live Console Terminal */}
            <div className="bg-[#08090d] border border-[#1e2433] rounded-lg p-4 font-mono">
              <div className="flex items-center justify-between pb-2 border-b border-[#1e2433] mb-3">
                <div className="flex items-center gap-2 text-xs text-zinc-400">
                  <Terminal className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="font-bold text-zinc-200">SOCKS5 PROBE LOG</span>
                </div>
                <span className="text-[10px] text-emerald-400 font-bold flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
                  STREAMING
                </span>
              </div>

              <div className="space-y-1 text-[10px] text-zinc-400 max-h-64 overflow-y-auto pr-1 scrollbar-thin leading-tight">
                {consoleLogs.map((log, i) => (
                  <div key={i}>
                    {log.startsWith('[SUCCESS]') ? (
                      <span className="text-emerald-400">{log}</span>
                    ) : log.startsWith('[ERROR]') ? (
                      <span className="text-rose-400">{log}</span>
                    ) : log.startsWith('[PROBE]') || log.startsWith('[TARGET]') ? (
                      <span className="text-amber-400">{log}</span>
                    ) : (
                      <span>{log}</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* No Active Scan Empty State */
        <div className="bg-[#0d1117] border border-[#1e2433] rounded-lg p-10 text-center">
          <Server className="w-10 h-10 text-zinc-600 mx-auto mb-3" />
          <h3 className="text-sm font-mono font-bold text-white uppercase tracking-wider mb-1">
            RECONNAISSANCE SCAN READY
          </h3>
          <p className="text-xs text-zinc-400 max-w-md mx-auto mb-4">
            Select a target service from the presets above or enter a custom .onion address to trigger the SOCKS5 infrastructure probe.
          </p>
          <button
            onClick={() => handleTrigger(customUrl)}
            disabled={isScanning || !customUrl}
            className="px-4 py-2 bg-amber-500 hover:bg-amber-400 disabled:bg-[#1e2433] text-black font-mono font-bold text-xs rounded transition-colors"
          >
            {isScanning ? 'SCANNING...' : 'EXECUTE SCAN NOW'}
          </button>
        </div>
      )}
    </div>
  );
};