import React, { useEffect, useState } from 'react';
import {
  Server,
  Terminal,
  AlertOctagon,
  Lock,
  Globe,
  Clock,
  Zap,
  AlertTriangle,
  CheckCircle2,
} from 'lucide-react';
import { InfraScanResult, ThreatActorCase } from '../types';

interface ModuleInfraScanProps {
  selectedCase: ThreatActorCase;
  scanResult?: InfraScanResult;
  onRunScan: (url: string) => Promise<void>;
  isScanning: boolean;
}

export const ModuleInfraScan: React.FC<ModuleInfraScanProps> = ({
  selectedCase,
  scanResult,
  onRunScan,
  isScanning,
}) => {
  const [customUrl, setCustomUrl] = useState('');
  const [consoleLogs, setConsoleLogs] = useState<string[]>([
    '[INIT] Infrastructure Scan Engine initialized with SOCKS5 Tor proxy.',
    '[READY] Loading Docker Tor testbed target...',
  ]);

  // Get the actual .onion address generated by the Docker Tor container.
  useEffect(() => {
    fetch('http://localhost:8000/api/testbed-target')
      .then(res => {
        if (!res.ok) {
          throw new Error(`Testbed API returned ${res.status}`);
        }
        return res.json();
      })
      .then(data => {
        if (data.onion_url) {
          setCustomUrl(data.onion_url);

          setConsoleLogs(prev => [
            ...prev,
            `[TARGET] Docker Tor testbed: ${data.onion_url}`,
            '[READY] Target loaded from live Tor hostname.',
          ]);
        } else {
          throw new Error('No onion address returned by backend');
        }
      })
      .catch(err => {
        console.error('Failed to load testbed target:', err);

        setConsoleLogs(prev => [
          ...prev,
          '[ERROR] Could not load Docker Tor testbed target.',
        ]);
      });
  }, []);

  const handleTrigger = async (urlToScan: string) => {
    if (!urlToScan) {
      setConsoleLogs(prev => [
        ...prev,
        '[ERROR] No .onion target available.',
      ]);
      return;
    }

    setCustomUrl(urlToScan);

    setConsoleLogs(prev => [
      ...prev,
      `[TASK] Scanning hidden service: ${urlToScan}`,
      '[STEP 1] Testing configured Tor service ports...',
      '[STEP 2] Probing HTTP server and status handlers...',
      '[STEP 3] Checking TLS certificate information if HTTPS is exposed...',
      '[STEP 4] Collecting infrastructure exposure indicators...',
    ]);

    try {
      await onRunScan(urlToScan);

      setConsoleLogs(prev => [
        ...prev,
        '[SUCCESS] Live infrastructure scan completed.',
      ]);
    } catch (error) {
      console.error('Infrastructure scan failed:', error);

      setConsoleLogs(prev => [
        ...prev,
        '[ERROR] Infrastructure scan failed.',
      ]);
    }
  };

  const statusPageDetails = scanResult?.statusPageDetails;

  return (
    <div className="space-y-6">

      {/* Engine Introduction Banner */}
      <div className="bg-[#121216] border border-white/[0.07] rounded-2xl p-6 flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-sm">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="px-2.5 py-0.5 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20 text-xs font-semibold">
              MODULE 1
            </span>

            <h2 className="text-xl font-bold text-white tracking-tight">
              Infrastructure Correlation Engine
            </h2>
          </div>

          <p className="text-xs text-zinc-400 max-w-2xl leading-relaxed">
            Performs live infrastructure reconnaissance against the controlled
            Docker Tor testbed using a SOCKS5 Tor connection. The scanner
            checks exposed ports, HTTP server banners, status pages, internal
            IP disclosures, and TLS certificate information.
          </p>
        </div>

        <div className="text-right">
          <div className="text-[11px] text-zinc-400 font-medium">
            LIVE SCAN STATUS
          </div>

          <div className="text-2xl font-bold font-mono text-amber-400">
            {scanResult ? scanResult.status : 'READY'}
          </div>
        </div>
      </div>

      {/* Target URL & Scanner */}
      <div className="bg-[#121216] border border-white/[0.07] rounded-2xl p-6 shadow-sm">

        <div className="text-xs text-zinc-400 mb-2 font-medium">
          Docker Tor Testbed Target
        </div>

        <div className="flex flex-col sm:flex-row gap-2.5 mb-3">
          <div className="relative flex-1">
            <input
              type="text"
              value={customUrl}
              onChange={(e) => setCustomUrl(e.target.value)}
              placeholder="Loading Tor testbed hostname..."
              className="w-full bg-[#0b0b0e] border border-white/[0.08] rounded-xl px-3.5 py-2.5 text-xs font-mono text-cyan-300 focus:outline-none focus:border-cyan-500/50 transition-colors"
            />
          </div>

          <button
            onClick={() => handleTrigger(customUrl)}
            disabled={isScanning || !customUrl}
            className="px-5 py-2.5 rounded-xl bg-amber-500/90 hover:bg-amber-400 disabled:bg-zinc-800 text-black disabled:text-zinc-500 font-semibold text-xs transition-all flex items-center justify-center gap-2 shadow-sm shadow-amber-950/40"
          >
            {isScanning ? (
              <>
                <span className="w-3.5 h-3.5 rounded-full border-2 border-black border-t-transparent animate-spin"></span>
                <span>Scanning...</span>
              </>
            ) : (
              <>
                <Zap className="w-4 h-4" />
                <span>Execute Misconfiguration Scan</span>
              </>
            )}
          </button>
        </div>

        <div className="flex items-center gap-2 text-[11px] font-mono text-gray-500">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400"></span>
          <span>
            Target automatically loaded from Docker Tor
          </span>
        </div>
      </div>

      {/* Live Scan Results */}
      {scanResult ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* Main Analysis */}
          <div className="lg:col-span-2 space-y-6">

            {/* Scan Summary */}
            <div className="bg-[#121216] border border-white/[0.07] rounded-2xl p-6 shadow-sm">

              <div className="flex items-center justify-between pb-4 border-b border-white/[0.06] mb-5">

                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400">
                    <Server className="w-5 h-5" />
                  </div>

                  <div>
                    <h3 className="text-base font-semibold text-white">
                      Live Infrastructure Scan
                    </h3>

                    <p className="text-xs text-zinc-400 mt-0.5 font-mono break-all">
                      {scanResult.onionUrl}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  {scanResult.status === 'ONLINE' ? (
                    <>
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      <span className="text-xs font-semibold text-emerald-400">
                        ONLINE
                      </span>
                    </>
                  ) : (
                    <span className="text-xs font-semibold text-rose-400">
                      OFFLINE
                    </span>
                  )}
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3.5">

                <div className="bg-[#0b0b0e] p-3.5 rounded-xl border border-white/[0.05]">
                  <div className="text-[11px] text-zinc-400 font-medium mb-1">
                    SERVER BANNER
                  </div>

                  <div className="text-sm font-bold text-cyan-400 font-mono break-all">
                    {scanResult.serverBanner || 'Not disclosed'}
                  </div>
                </div>

                <div className="bg-[#0b0b0e] p-3.5 rounded-xl border border-white/[0.05]">
                  <div className="text-[11px] text-zinc-400 font-medium mb-1">
                    OPEN PORTS
                  </div>

                  <div className="text-sm font-bold text-amber-400 font-mono">
                    {scanResult.openPorts.length > 0
                      ? scanResult.openPorts.join(', ')
                      : 'None detected'}
                  </div>
                </div>

                <div className="bg-[#0b0b0e] p-3.5 rounded-xl border border-white/[0.05]">
                  <div className="text-[11px] text-zinc-400 font-medium mb-1">
                    STATUS PAGE
                  </div>

                  <div className={`text-sm font-bold font-mono ${
                    scanResult.exposedStatusPage
                      ? 'text-rose-400'
                      : 'text-emerald-400'
                  }`}>
                    {scanResult.exposedStatusPage
                      ? 'EXPOSED'
                      : 'NOT DETECTED'}
                  </div>
                </div>

              </div>
            </div>

            {/* Apache / HTTP Analysis */}
            <div className="bg-[#121216] border border-white/[0.07] rounded-2xl p-6 shadow-sm">

              <h3 className="text-sm font-bold text-white mb-4 font-mono flex items-center gap-2">
                <Server className="w-4 h-4 text-amber-400" />
                Web Server Status &amp; Banner Analysis
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">

                {/* Banner */}
                <div className="bg-[#0c0c0e] p-3 rounded-lg border border-[#1e1e24]">
                  <div className="text-[10px] font-mono text-gray-500">
                    SERVER HTTP BANNER
                  </div>

                  <div className="text-xs font-mono text-gray-200 mt-1 break-all bg-[#141417] p-2 rounded border border-[#1e1e24]">
                    {scanResult.serverBanner || 'Not disclosed'}
                  </div>
                </div>

                {/* Status Handler */}
                <div className="bg-[#0c0c0e] p-3 rounded-lg border border-[#1e1e24]">

                  <div className="text-[10px] font-mono text-gray-500">
                    STATUS HANDLER EXPOSURE
                  </div>

                  <div className="flex items-center gap-2 mt-1">

                    <span
                      className={`px-2 py-0.5 rounded text-xs font-mono font-bold ${
                        scanResult.exposedStatusPage
                          ? 'bg-rose-950/60 text-rose-300 border border-rose-800/60'
                          : 'bg-[#1a1a1f] text-gray-400'
                      }`}
                    >
                      {scanResult.exposedStatusPage
                        ? '/server-status EXPOSED'
                        : 'NOT DETECTED'}
                    </span>

                  </div>

                  {statusPageDetails?.serverUptime && (
                    <div className="mt-2 text-[11px] font-mono text-gray-300">
                      Server uptime: {statusPageDetails.serverUptime}
                    </div>
                  )}

                  {statusPageDetails?.internalIPs &&
                    statusPageDetails.internalIPs.length > 0 && (
                      <div className="mt-2 text-[11px] font-mono text-rose-300">
                        Disclosed internal IPs:{' '}
                        {statusPageDetails.internalIPs.join(', ')}
                      </div>
                    )}

                </div>
              </div>

              {/* Status Page Finding */}
              {scanResult.exposedStatusPage && (
                <div className="mt-4 bg-rose-500/5 border border-rose-500/20 rounded-xl p-4">

                  <div className="flex items-center gap-2 text-rose-300 text-xs font-semibold mb-2">
                    <AlertOctagon className="w-4 h-4" />
                    Exposed Apache Status Handler Detected
                  </div>

                  <p className="text-xs text-rose-200/80 leading-relaxed">
                    The live testbed exposed the Apache
                    <span className="font-mono"> /server-status </span>
                    endpoint. The scanner also detected the server's runtime
                    information and any internal IP addresses present in the
                    response.
                  </p>
                </div>
              )}

              {/* TLS */}
              {scanResult.sslCertificate &&
                scanResult.sslCertificate.hasSsl && (
                  <div className="border-t border-[#1e1e24] pt-4 mt-5">

                    <div className="text-xs font-mono text-gray-400 mb-2 flex items-center gap-1.5">
                      <Lock className="w-3.5 h-3.5 text-cyan-400" />
                      <span>X.509 TLS CERTIFICATE INFORMATION</span>
                    </div>

                    <div className="bg-[#0c0c0e] p-3.5 rounded-lg border border-[#1e1e24] text-xs font-mono space-y-2">

                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 pb-2 border-b border-[#1e1e24]">
                        <span className="text-gray-400">
                          SHA-256 Fingerprint:
                        </span>

                        <span className="text-amber-300 break-all">
                          {scanResult.sslCertificate.sha256Fingerprint}
                        </span>
                      </div>

                    </div>
                  </div>
                )}

            </div>
          </div>

          {/* Right Column */}
          <div className="space-y-6">

            {/* Port Recon */}
            <div className="bg-[#141417] border border-[#1e1e24] rounded-xl p-5 shadow-lg">

              <h3 className="text-sm font-bold text-white mb-3 font-mono flex items-center gap-2">
                <Globe className="w-4 h-4 text-cyan-400" />
                <span>Port Recon</span>
              </h3>

              <div>
                <div className="text-[11px] font-mono text-gray-400 mb-1.5">
                  OPEN PORTS DETECTED
                </div>

                <div className="flex items-center gap-2 flex-wrap">

                  {scanResult.openPorts.length > 0 ? (
                    scanResult.openPorts.map((port) => (
                      <span
                        key={port}
                        className="px-2.5 py-1 rounded bg-[#0c0c0e] text-cyan-300 border border-[#1e1e24] font-mono text-xs flex items-center gap-1"
                      >
                        <span className="w-1.5 h-1.5 rounded-full bg-cyan-400"></span>
                        <span>Port {port}</span>
                      </span>
                    ))
                  ) : (
                    <span className="text-xs text-gray-500">
                      No open ports detected
                    </span>
                  )}

                </div>
              </div>

              <div className="pt-4 mt-4 border-t border-[#1e1e24]">

                <div className="text-[11px] font-mono text-gray-400 mb-1 flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5 text-amber-400" />
                  <span>SCAN TIMESTAMP</span>
                </div>

                <div className="bg-[#0c0c0e] p-2.5 rounded border border-[#1e1e24] font-mono text-xs text-gray-300">
                  {scanResult.testedAt}
                </div>

              </div>
            </div>

            {/* Live Console */}
            <div className="bg-[#0a0a0c] border border-[#1e1e24] rounded-xl p-4 font-mono shadow-lg">

              <div className="flex items-center justify-between pb-2 border-b border-[#1e1e24] mb-2">

                <div className="text-xs text-gray-400 flex items-center gap-1.5">
                  <Terminal className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Infrastructure Scan Log</span>
                </div>

                <span className="text-[10px] text-emerald-400">
                  LIVE
                </span>

              </div>

              <div className="space-y-1.5 text-[11px] text-gray-300 max-h-72 overflow-y-auto pr-1 scrollbar-thin">

                {consoleLogs.map((log, i) => (
                  <div key={i} className="leading-tight">
                    {log.startsWith('[SUCCESS]') ? (
                      <span className="text-emerald-400">{log}</span>
                    ) : log.startsWith('[ERROR]') ? (
                      <span className="text-rose-400">{log}</span>
                    ) : log.startsWith('[TASK]') ||
                      log.startsWith('[TARGET]') ? (
                      <span className="text-amber-400">{log}</span>
                    ) : (
                      <span className="text-gray-400">{log}</span>
                    )}
                  </div>
                ))}

              </div>
            </div>

          </div>
        </div>
      ) : (
        /* No Results */
        <div className="bg-[#141417] border border-[#1e1e24] rounded-xl p-12 text-center shadow-lg">

          <Server className="w-12 h-12 text-gray-600 mx-auto mb-3" />

          <h3 className="text-base font-bold text-white mb-1">
            No Active Scan Results
          </h3>

          <p className="text-xs text-gray-400 mb-4 max-w-md mx-auto">
            The target above is loaded directly from the Docker Tor testbed.
            Execute the scan to collect live infrastructure data.
          </p>

          <button
            onClick={() => handleTrigger(customUrl)}
            disabled={isScanning || !customUrl}
            className="px-4 py-2 bg-amber-600 hover:bg-amber-500 disabled:bg-zinc-800 text-black disabled:text-zinc-500 font-bold text-xs font-mono rounded-lg transition"
          >
            {isScanning ? 'Scanning...' : 'Run Scan Now'}
          </button>

        </div>
      )}
    </div>
  );
};