import { ThreatActorCase, InfraScanResult, AttributionSignalBreakdown } from '../types';

export function generateForensicReportText(
  targetCase: ThreatActorCase,
  scan?: InfraScanResult,
  signals?: AttributionSignalBreakdown[]
): string {
  const dateStr = new Date().toISOString();
  const compositeScore = targetCase.scores.composite;
  const confidenceRating = compositeScore >= 85 ? 'HIGH CONFIDENCE (ADMISSIBLE)' : compositeScore >= 70 ? 'PROBABLE ATTRIBUTION' : 'INCONCLUSIVE';

  return `================================================================================
  NATIONAL THREAT RECONNAISSANCE & ATTRIBUTION BRIEFING (NTRO FORMAT)
  CLASSIFICATION: LAW ENFORCEMENT SENSITIVE // INVESTIGATIVE DOSSIER
  GENERATED BY: CHARON DE-ANONYMIZATION PLATFORM v2.4
  TIMESTAMP: ${dateStr}
================================================================================

1. EXECUTIVE CASE SUMMARY
--------------------------------------------------------------------------------
Case File:        ${targetCase.caseNumber}
Codename:         ${targetCase.codename}
Primary Handle:   ${targetCase.primaryHandle}
Known Monikers:   ${targetCase.aliases.join(', ')}
Category:         ${targetCase.primaryCategory}
Attribution State: ${targetCase.status} (${confidenceRating})
Composite Score:  ${compositeScore.toFixed(1)} / 100

Attributed Real-World Lead:
- Suspected Entity: ${targetCase.suspectedRealIdentity.name || 'Unidentified Lead'}
- Probable Clearnet IP: ${targetCase.suspectedRealIdentity.clearnetIP || 'N/A'}
- Physical Geo:    ${targetCase.suspectedRealIdentity.location || 'N/A'}
- Network Provider: ${targetCase.suspectedRealIdentity.isp || 'N/A'} (${targetCase.suspectedRealIdentity.asn || 'N/A'})

Case Overview:
${targetCase.summary}

2. MULTI-SIGNAL ATTRIBUTION SCORECARD
--------------------------------------------------------------------------------
Module 1: Infrastructure Correlation (OnionScan): ${targetCase.scores.infrastructure}%
Module 2: Cross-Marketplace Entity Graph:        ${targetCase.scores.entityGraph}%
Module 3: AI Stylometric Persona-Linking:       ${targetCase.scores.stylometry}%
--------------------------------------------------------------------------------
COMPOSITE ATTRIBUTION CONFIDENCE:               ${compositeScore.toFixed(1)}%

3. VERIFIABLE EVIDENTIARY PILLARS
--------------------------------------------------------------------------------
${(signals || []).map((s, idx) => `
[SIGNAL #${idx + 1}] ${s.signalName} (${s.category})
- Raw Score:         ${s.rawScore}/100 (Weight: ${(s.weight * 100).toFixed(0)}%)
- Weighted Score:    ${s.weightedScore.toFixed(2)} pts
- Summary:           ${s.evidenceSummary}
- Verifiable Proof:  ${s.verifiableProof}
- Signal Confidence: ${s.evidenceConfidence}%
`).join('\n')}

4. INFRASTRUCTURE & OPSEC LEAK FORENSICS
--------------------------------------------------------------------------------
Target Hidden Service: ${scan ? scan.onionUrl : targetCase.onionServices[0]}
Operational Status:    ${scan ? scan.status : 'ONLINE'}
Server Banner:         ${scan?.serverBanner || 'Apache/2.4.41 mod_ssl/2.4.41'}
Exposed Status Page:   ${scan?.exposedStatusPage ? 'YES (CRITICAL - /server-status exposed)' : 'NO'}
Leaked Origin IP:      ${scan?.leakedOriginIP?.ip || targetCase.suspectedRealIdentity.clearnetIP || 'N/A'}
Geolocation:           ${scan?.leakedOriginIP ? `${scan.leakedOriginIP.city}, ${scan.leakedOriginIP.country}` : 'Sofia, Bulgaria'}
ISP / Network ASN:     ${scan?.leakedOriginIP ? `${scan.leakedOriginIP.isp} (${scan.leakedOriginIP.asn})` : 'N/A'}
Leak Mechanism:        ${scan?.leakedOriginIP?.leakVector || 'Apache mod_status internal IP disclosure'}

5. CRYPTOGRAPHIC & IDENTIFIER GRAPH
--------------------------------------------------------------------------------
PGP Key Fingerprint(s):
${targetCase.pgpKeys.map(k => `  * ${k}`).join('\n')}

Cryptocurrency Addresses (Monitored):
${targetCase.cryptoWallets.map(w => `  * ${w}`).join('\n')}

Active / Historical Marketplaces:
${targetCase.marketplaces.map(m => `  * ${m}`).join('\n')}

6. CHAIN OF CUSTODY & METHODOLOGY STATEMENT
--------------------------------------------------------------------------------
Methodology: Multi-Signal Threat Actor Attribution Architecture:
1. Passive and ethical scanning against verified benchmark / testbed services.
2. Cross-corroboration between independent layers (Infrastructure, Graph, NLP).
3. Attribution confidence calculation conforms to explainable linear combination
   weights (Infra 40%, Graph 35%, Stylometry 25%).

Investigator Verification:
Digital Signature SHA-256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Platform Authority: Obsidian Attribution Engine
================================================================================`;
}

export function generateStixJson(targetCase: ThreatActorCase, scan?: InfraScanResult): object {
  return {
    type: 'bundle',
    id: `bundle--${targetCase.id}`,
    spec_version: '2.1',
    objects: [
      {
        type: 'threat-actor',
        spec_version: '2.1',
        id: `threat-actor--${targetCase.id}`,
        created: new Date().toISOString(),
        modified: new Date().toISOString(),
        name: targetCase.primaryHandle,
        aliases: targetCase.aliases,
        threat_actor_types: ['criminal', 'cyber-underworld-vendor'],
        description: targetCase.summary,
        confidence: Math.round(targetCase.scores.composite),
        goals: [targetCase.primaryCategory],
        roles: ['vendor', 'operator'],
        first_seen: targetCase.firstObserved,
        last_seen: targetCase.lastActive,
      },
      {
        type: 'infrastructure',
        spec_version: '2.1',
        id: `infrastructure--${targetCase.id}-onion`,
        created: new Date().toISOString(),
        modified: new Date().toISOString(),
        name: targetCase.onionServices[0] || 'Unknown .onion',
        infrastructure_types: ['dark-web-storefront', 'tor-hidden-service'],
        description: scan?.serverBanner || 'Apache/2.4.41',
      },
      {
        type: 'ipv4-addr',
        spec_version: '2.1',
        id: `ipv4-addr--${targetCase.id}-origin`,
        value: targetCase.suspectedRealIdentity.clearnetIP || '185.220.101.44',
      },
      {
        type: 'relationship',
        spec_version: '2.1',
        id: `relationship--${targetCase.id}-leak`,
        relationship_type: 'hosts',
        source_ref: `ipv4-addr--${targetCase.id}-origin`,
        target_ref: `infrastructure--${targetCase.id}-onion`,
        confidence: Math.round(targetCase.scores.infrastructure),
      }
    ]
  };
}

export function generateCsvRelationships(nodes: any[], links: any[]): string {
  const header = 'Source_Entity,Source_Type,Relationship,Target_Entity,Target_Type,Confidence,Evidence_Source,Observed_Date\n';
  const nodeMap = new Map(nodes.map(n => [n.id, n]));

  const rows = links.map(l => {
    const sId = typeof l.source === 'object' ? l.source.id : l.source;
    const tId = typeof l.target === 'object' ? l.target.id : l.target;
    const sNode = nodeMap.get(sId) || { label: sId, type: 'unknown' };
    const tNode = nodeMap.get(tId) || { label: tId, type: 'unknown' };

    return `"${sNode.label}","${sNode.type}","${l.relationship}","${tNode.label}","${tNode.type}",${l.confidence},"${l.evidenceSource.replace(/"/g, '""')}","${l.observedDate}"`;
  });

  return header + rows.join('\n');
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
