import React, { useEffect, useState } from 'react';
import { Header } from './components/Header';
import { SetupPage } from './components/SetupPage';
import { CaseOverview } from './components/CaseOverview';
import { ModuleInfraScan } from './components/ModuleInfraScan';
import { ModuleEntityGraph } from './components/ModuleEntityGraph';
import { ModuleStylometry } from './components/ModuleStylometry';
import { FusionLayer } from './components/FusionLayer';
import { InvestigationTimeline } from './components/InvestigationTimeline';
import { ReportExportModal } from './components/ReportExportModal';
import { NewTargetModal } from './components/NewTargetModal';
import {
  BENCHMARK_CASES,
  MOCK_GRAPH_DATA,
  MOCK_TIMELINES,
  MOCK_FUSION_SIGNALS
} from './data/mockData';
import { ThreatActorCase, InfraScanResult, GraphNode, GraphLink } from './types';

export default function App() {
  const [cases, setCases] = useState<ThreatActorCase[]>(BENCHMARK_CASES);
  const [selectedCase, setSelectedCase] = useState<ThreatActorCase>(BENCHMARK_CASES[0]);
  
  // Tab union and declared activeTarget & activeMode states
  const [activeTab, setActiveTab] = useState<
    'overview' | 'setup' | 'infra' | 'graph' | 'stylometry' | 'fusion' | 'timeline'
  >('overview');
  const [activeTarget, setActiveTarget] = useState<string>('');
  const [activeMode, setActiveMode] = useState<'testbed' | 'manual'>('testbed');

  // Live infrastructure scan results
  const [scanResults, setScanResults] = useState<Record<string, InfraScanResult>>({});
  const [isScanning, setIsScanning] = useState(false);

  // Real .onion address generated by the Docker Tor testbed
  const [testbedOnion, setTestbedOnion] = useState<string>('');

  const [exportModalOpen, setExportModalOpen] = useState(false);
  const [newTargetModalOpen, setNewTargetModalOpen] = useState(false);

  // Live entity graph data state
  const [liveGraphData, setLiveGraphData] = useState<{ nodes: GraphNode[]; links: GraphLink[] } | null>(null);

  // Fetch live graph data whenever the graph tab is opened
  useEffect(() => {
    if (activeTab !== 'graph') return;
    fetch('http://localhost:8000/api/entity-graph')
      .then(res => res.json())
      .then(data => setLiveGraphData(data.nodes.length > 0 ? data : null))
      .catch(() => setLiveGraphData(null));
  }, [activeTab]);

  // Get the current .onion address directly from the Tor testbed
  useEffect(() => {
    fetch('http://localhost:8000/api/testbed-target')
      .then(res => {
        if (!res.ok) {
          throw new Error(`Testbed API returned ${res.status}`);
        }
        return res.json();
      })
      .then(data => {
        if (data.onion_url) {
          setTestbedOnion(data.onion_url);
          // Default activeTarget to the testbed onion address on load
          setActiveTarget(data.onion_url);
          console.log('Tor testbed target:', data.onion_url);
        } else {
          console.error('No onion address returned by testbed');
        }
      })
      .catch(err => {
        console.error('Failed to get testbed onion:', err);
      });
  }, []);

  // Active target data
  const currentScan = scanResults[selectedCase.id];
  const currentGraphData =
    liveGraphData ?? MOCK_GRAPH_DATA[selectedCase.id] ?? MOCK_GRAPH_DATA['case-venom-01'];
  const isLiveGraph = liveGraphData !== null;

  const currentTimeline =
    MOCK_TIMELINES[selectedCase.id] || MOCK_TIMELINES['case-venom-01'];
  const currentSignals =
    MOCK_FUSION_SIGNALS[selectedCase.id] || MOCK_FUSION_SIGNALS['case-venom-01'];

  // Run infrastructure scan through the real backend
  const handleRunScan = async (onionUrl: string) => {
    if (!onionUrl) {
      console.error('No Tor target onion address available');
      return;
    }

    setIsScanning(true);

    try {
      const res = await fetch('http://localhost:8000/api/infra-scan', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          onion_url: onionUrl,
        }),
      });

      if (!res.ok) {
        throw new Error(`Scan API returned ${res.status}`);
      }

      const data: InfraScanResult = await res.json();

      setScanResults(prev => ({
        ...prev,
        [selectedCase.id]: data,
      }));
    } catch (err) {
      console.error('Scan failed:', err);
    } finally {
      setIsScanning(false);
      setActiveTab('infra');
    }
  };

  const handleCreateTarget = (newCase: ThreatActorCase) => {
    setCases(prev => [newCase, ...prev]);
    setSelectedCase(newCase);
    setActiveTab('overview');
  };

  return (
    <div className="min-h-screen bg-[#0a0a0c] text-gray-300 flex flex-col selection:bg-cyan-500 selection:text-black font-sans">

      {/* Top Main Navigation Header */}
      <Header
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        cases={cases}
        selectedCase={selectedCase}
        setSelectedCase={setSelectedCase}
        onOpenExport={() => setExportModalOpen(true)}
        onOpenNewTarget={() => setNewTargetModalOpen(true)}
      />

      {/* Main Content Area */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 py-6">

        {activeTab === 'overview' && (
          <CaseOverview
            targetCase={selectedCase}
            onNavigateTab={(tab) => setActiveTab(tab)}
            onRunScan={() => handleRunScan(activeTarget)}
          />
        )}

        {activeTab === 'setup' && (
          <SetupPage
            testbedOnion={testbedOnion}
            activeTarget={activeTarget}
            activeMode={activeMode}
            onSetTarget={(url, mode) => {
              setActiveTarget(url);
              setActiveMode(mode);
            }}
          />
        )}

        {activeTab === 'infra' && (
          <ModuleInfraScan
            selectedCase={selectedCase}
            scanResult={scanResults[selectedCase.id]}
            onRunScan={handleRunScan}
            isScanning={isScanning}
          />
        )}

        {activeTab === 'graph' && (
          <ModuleEntityGraph
            selectedCase={selectedCase}
            graphData={currentGraphData}
            isLiveGraph={isLiveGraph}
          />
        )}

        {activeTab === 'stylometry' && (
          <ModuleStylometry
            selectedCase={selectedCase}
          />
        )}

        {activeTab === 'fusion' && (
          <FusionLayer
            selectedCase={selectedCase}
            signals={currentSignals}
            onOpenExport={() => setExportModalOpen(true)}
            onNavigateTab={(tab) => setActiveTab(tab)}
          />
        )}

        {activeTab === 'timeline' && (
          <InvestigationTimeline
            selectedCase={selectedCase}
            timelineEvents={currentTimeline}
          />
        )}
      </main>

      {/* Operational Status Footer */}
      <footer className="border-t border-white/[0.06] bg-[#0c0c0f]/80 backdrop-blur-sm py-4 px-4 sm:px-6 mt-auto text-xs text-zinc-500">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
            <span className="text-zinc-300 font-semibold tracking-wide">
              OBSIDIAN PLATFORM v2.4
            </span>
            <span className="text-zinc-700">&bull;</span>
            <span className="text-zinc-400">
              National Technical Research Organisation (NTRO)
            </span>
          </div>

          <div className="flex items-center gap-4">
            <span className="text-zinc-400 font-mono text-[11px]">
              System Status: Operational
            </span>
          </div>
        </div>
      </footer>

      {/* Dossier Export Modal */}
      <ReportExportModal
        isOpen={exportModalOpen}
        onClose={() => setExportModalOpen(false)}
        targetCase={selectedCase}
        scan={currentScan}
        signals={currentSignals}
        graphData={currentGraphData}
      />

      {/* Custom Target Creation Modal */}
      <NewTargetModal
        isOpen={newTargetModalOpen}
        onClose={() => setNewTargetModalOpen(false)}
        onCreateTarget={handleCreateTarget}
      />
    </div>
  );
}
